<%@ Page Title="" Language="C#" MasterPageFile="~/Views/Seller/Seller.Master" AutoEventWireup="true" CodeBehind="Billing.aspx.cs" Inherits="Health_Care_Pharmacy.Views.Seller.Billing" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="container-fluid">
        <div class="row">
            <h4 class="text_success">Online Pharmacy Billing</h4>
        </div>
        <div class="row">
            <div class="col-md-4">
                        <div class="row mb-3">
                            <div class="col">
                                <asp:Label ID="Label1" runat="server" Text="Medicine Code"></asp:Label>
                                <asp:TextBox ID="Med_Code_Txt" type="text" class="form-control" placeholder="Medicine Code" aria-label="First name" runat="server"></asp:TextBox>
                            </div>
                            <div class="col">
                                <asp:Label ID="Label2" runat="server" Text="Medicine Name"></asp:Label>
                                <asp:TextBox ID="Med_Name_Txt" type="text" class="form-control" placeholder="Medicine Name" aria-label="Last name" runat="server"></asp:TextBox>
                            </div>
                         </div>
                        <div class="row mb-3">
                            <div class="col">
                                <asp:Label ID="Label3" runat="server" Text="Medicine Quantity"></asp:Label>
                                <asp:TextBox ID="Med_Quantity_Txt" type="text" class="form-control" placeholder="Medicine Quantity" aria-label="First name" runat="server"></asp:TextBox>
                            </div>
                            <div class="col">
                                <asp:Label ID="Label4" runat="server" Text="Billing Date"></asp:Label>
                                <asp:TextBox ID="Bill_Date_Txt" type="date" class="form-control"  aria-label="Last name" runat="server"></asp:TextBox>
                            </div>
                         </div>
                <div class="row">
                    <div class="col d-grid">
                        <asp:Button ID="Button1" class="btn btn-success btn-block" runat="server" Text="Add To Bill" OnClick="Button1_Click" />
                    </div>
                    <div class="col d-grid">
                        <asp:Button ID="Button2" class="btn btn-danger btn-block" runat="server" Text="Reset" OnClick="Button2_Click" />
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <h2>Categories List</h2>
                        <asp:GridView ID="Category_List" class="table table_success" runat="server" AutoGenerateSelectButton="True" OnSelectedIndexChanged="Category_List_SelectedIndexChanged" CellPadding="4" ForeColor="#333333" GridLines="None">
                            <AlternatingRowStyle BackColor="White" />
                            <EditRowStyle BackColor="#7C6F57" />
                            <FooterStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
                            <HeaderStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
                            <PagerStyle BackColor="#666666" ForeColor="White" HorizontalAlign="Center" />
                            <RowStyle BackColor="#E3EAEB" />
                            <SelectedRowStyle BackColor="#C5BBAF" Font-Bold="True" ForeColor="#333333" />
                            <SortedAscendingCellStyle BackColor="#F8FAFA" />
                            <SortedAscendingHeaderStyle BackColor="#246B61" />
                            <SortedDescendingCellStyle BackColor="#D4DFE1" />
                            <SortedDescendingHeaderStyle BackColor="#15524A" />
                        </asp:GridView>
                    </div>
                </div>
            </div>
            <div class="col-md-8">
                <h2 class="text-center text-success" >Client's List</h2>
                <asp:GridView ID="Bill_List" class="table table_success" runat="server" AutoGenerateSelectButton="True" OnSelectedIndexChanged="Category_List_SelectedIndexChanged" AutoGenerateDeleteButton="True" CellPadding="4" ForeColor="#333333" GridLines="None">
                    <AlternatingRowStyle BackColor="White" />
                    <EditRowStyle BackColor="#7C6F57" />
                    <FooterStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
                    <HeaderStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#666666" ForeColor="White" HorizontalAlign="Center" />
                    <RowStyle BackColor="#E3EAEB" />
                    <SelectedRowStyle BackColor="#C5BBAF" Font-Bold="True" ForeColor="#333333" />
                    <SortedAscendingCellStyle BackColor="#F8FAFA" />
                    <SortedAscendingHeaderStyle BackColor="#246B61" />
                    <SortedDescendingCellStyle BackColor="#D4DFE1" />
                    <SortedDescendingHeaderStyle BackColor="#15524A" />
                </asp:GridView>
                <div class="row">
                <div class="col-5"></div>
                <div class="col-5">
                     <asp:Label ID="Grand_Lable" class="h5 text-danger text-center" runat="server" Text="Label"></asp:Label>
                </div>
                    </div>
               
            <div class="row">
                <div class="col d-grid">
                    <asp:Button ID="Button3" class="btn btn-success btn-block" runat="server" Text="Print" OnClick="Button3_Click" />
                </div>
                <div class="col d-grid">
                    <asp:Button ID="Button4" class="btn btn-warning btn-block" runat="server" Text="Clear" OnClick="Button4_Click" />
                </div>
            </div>
            </div>
        </div>
    </div>
</asp:Content>
